### ISSUE TITLE
stripAll() method doesn't really strip ALL

### ISSUE THREAD

**Issue by kevinwojo** [hubzero/framework#105]
In: https://github.com/hubzero/framework/blob/master/src/Utility/Sanitize.php#L139
It's not obvious to me why stripTags() is not included in the stripAll() method.

**Comment by zooley** [comment]
stripTags() currently only strips defined tags. If I remember correctly, it was a later addition, primarily to replace some tag stripping in the clean() method. I suppose it could be made so that, if no list of tags is provided, it does a strip_tags(). In which case, it could then be included in stripAll().

**Comment by zooley** [comment]
stripTags added to stripAll
