### ISSUE TITLE
Specility

### ISSUE THREAD

**Issue by tisuchi** [hubzero/framework#398]
Hello 

Nice work. 

However, how do you distinguish hubzero against Laravel / CodeIgnitor?

**Comment by zooley** [comment]
HUBzero has borrowed ideas from both and leans towards how Laravel operates. There are key differences, however. One of the biggest is in how code (e.g., extensions to the HUBzero CMS) is organized. For CMSes like Laravel, Codeigniter, CakePHP, etc., there tens to be a single place for controllers, a single location for views, models, and so on. The HUBzero CMS allows for complete mini applications such as a forum or blog to be contained within their own folder, rather than separating out controllers, models, and views into shared folders with other code. This allows for easier installation, management, and removal of extensions.
